[env:esp32s3]
platform = espressif32
board = esp32-s3-devkitc-1
framework = espidf
monitor_speed = 115200
build_flags =
  -DCORE_DEBUG=1
  -I include

[env:single_mcu]
extends = env:esp32s3
build_flags =  -DPROFILE_SINGLE_MCU

[env:split_mcu_main]
extends = env:esp32s3
build_flags =  -DPROFILE_SPLIT_MAIN

[env:display_mcu]
platform = espressif32
board = esp32-s3-devkitc-1
framework = espidf
build_flags = -DDISPLAY_MCU
monitor_speed = 115200
