[platformio]
default_envs = single_mcu
src_dir = main

[env:single_mcu]
platform = espressif32
board = esp32-s3-devkitc-1
framework = espidf
monitor_speed = 115200
board_build.partitions = partitions.csv
board_upload.flash_size = 16MB
build_flags =
  -DCORE_DEBUG=1
  -DCONFIG_AUDIO_TEST_SIMULATION=1
  -I include
  -I components/chronolink_hal/include
  -I src/platformDependentLayer
  -DPROFILE_SINGLE_MCU

board_build.filesystem = fatfs

[env:split_mcu_main]
platform = espressif32
board = esp32-s3-devkitc-1
framework = espidf
monitor_speed = 115200
board_build.partitions = partitions.csv
board_upload.flash_size = 16MB
build_flags =
  -DCORE_DEBUG=1
  -I include
  -DPROFILE_SPLIT_MAIN

[env:display_mcu]
platform = espressif32
board = esp32-s3-devkitc-1
framework = espidf
monitor_speed = 115200
board_build.partitions = partitions.csv
board_upload.flash_size = 16MB
build_flags =
  -DCORE_DEBUG=1
  -I include
  -DDISPLAY_MCU